services:
  nginx:
    image: nginx:alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    env_file:
      - ./.env
    command: node src/index.js

  redis:
    image: redis